In [28]:
import pandas as pd
import sqlite3
import numpy as np

conn = sqlite3.connect("kickbase.db")

query = "SELECT * FROM player_stats_field"

df = pd.read_sql_query(query, conn)

conn.close()
    
df = df.sort_values(by=['player_id', 'season', 'matchday']).reset_index(drop=True)

In [29]:
df["points_filled"] = df['points'].fillna(0)

In [30]:
df["points_avg_last_3"] = (
    df.groupby(["player_id", "season"])["points_filled"] 
    .shift(1)
    .rolling(window=3)
    .mean()
)

In [31]:
df["points_avg_last_5"] = (
    df.groupby(["player_id", "season"])["points_filled"]
    .shift(1)
    .rolling(window=5)
    .mean()
)

In [32]:
df["points_trend"] = df["points_avg_last_3"] - df["points_avg_last_5"]

In [33]:
df[["player_id", "matchday", "points", "points_avg_last_3", "points_avg_last_5", "points_trend"]].head(20)

,player_id,matchday,points,points_avg_last_3,points_avg_last_5,points_trend
0,1,1,46.0,NaN,NaN,NaN
1,1,2,40.0,NaN,NaN,NaN
2,1,3,34.0,NaN,NaN,NaN
3,1,4,92.0,40.000000,NaN,NaN
4,1,5,99.0,55.333333,NaN,NaN
5,1,6,52.0,75.000000,62.2,12.800000
6,1,7,70.0,81.000000,63.4,17.600000
7,1,8,70.0,73.666667,69.4,4.266667
8,1,9,144.0,64.000000,76.6,-12.600000
9,1,10,31.0,94.666667,87.0,7.666667
10,1,11,57.0,81.666667,73.4,8.266667
11,1,12,41.0,77.333333,74.4,2.933333
12,1,13,46.0,43.000000,68.6,-25.600000
13,1,14,39.0,48.000000,63.8,-15.800000
14,1,15,151.0,42.000000,42.8,-0.800000
15,1,16,97.0,78.666667,66.8,11.866667
16,1,17,71.0,95.666667,74.8,20.866667
17,1,18,108.0,106.333333,80.8,25.533333
18,1,19,149.0,92.000000,93.2,-1.200000
19,1,20,46.0,109.333333,115.2,-5.866667

In [34]:
df = df.drop(columns=["points_filled"])

In [35]:
df["minutes_filled"] = df["minutes"].fillna(0)

In [36]:
df["minutes_avg_last_3"] = (
    df.groupby(["player_id", "season"])["minutes_filled"]
    .shift(1)
    .rolling(window=3)
    .mean()
)

In [37]:
df["minutes_avg_last_5"] = (
    df.groupby(["player_id", "season"])["minutes_filled"]
    .shift(1)
    .rolling(window=5)
    .mean()
)

In [38]:
df[["player_id", "matchday", "minutes", "minutes_avg_last_3", "minutes_avg_last_5"]].head(20)

    player_id  matchday  minutes  minutes_avg_last_3  minutes_avg_last_5
0           1         1       93                 NaN                 NaN
1           1         2       96                 NaN                 NaN
2           1         3       99                 NaN                 NaN
3           1         4       94           96.000000                 NaN
4           1         5       99           96.333333                 NaN
5           1         6       98           97.333333                96.2
6           1         7      100           97.000000                97.2
7           1         8       97           99.000000                98.0
8           1         9       95           98.333333                97.6
9           1        10       94           97.333333                97.8
10          1        11       95           95.333333                96.8
11          1        12       98           94.666667                96.2
12          1        13       96           95.666667                95.8
13          1        14      109           96.333333                95.6
14          1        15       99          101.000000                98.4
15          1        16       99          101.333333                99.4
16          1        17       99          102.333333               100.2
17          1        18       99           99.000000               100.4
18          1        19       95           99.000000               101.0
19          1        20       98           97.666667                98.2

In [39]:
df.drop(columns=["minutes_filled"])

,id,player_id,season,matchday,date,points,minutes,points_per_minute,market_value,points_per_value,...,schuesse_aufs_tor,schussgenauigkeit,schussgenauigkeit_gesamt,fehler_vor_gegentor,geblockte_baelle,points_avg_last_3,points_avg_last_5,points_trend,minutes_avg_last_3,minutes_avg_last_5
0,32,1,2024/2025,1,2024-08-25T15:30:00Z,46.0,93,0.494624,None,NaN,...,1,1,1,0,0,NaN,NaN,NaN,NaN,NaN
1,33,1,2024/2025,2,2024-08-30T18:30:00Z,40.0,96,0.416667,None,NaN,...,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN
2,34,1,2024/2025,3,2024-09-15T13:30:00Z,34.0,99,0.343434,None,NaN,...,0,0,0,0,1,NaN,NaN,NaN,NaN,NaN
3,35,1,2024/2025,4,2024-09-22T17:30:00Z,92.0,94,0.978723,None,NaN,...,0,0,0,0,0,40.000000,NaN,NaN,96.000000,NaN
4,36,1,2024/2025,5,2024-09-28T13:30:00Z,99.0,99,1.000000,None,NaN,...,0,0,0,0,1,55.333333,NaN,NaN,96.333333,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20939,21265,3703,2025/2026,30,2026-04-19T15:30:00Z,16.0,9,1.777778,None,0.000032,...,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN
20940,21266,3703,2025/2026,31,2026-04-25T13:30:00Z,NaN,0,NaN,None,NaN,...,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN
20941,21267,3704,2025/2026,29,2026-04-11T16:30:00Z,48.0,12,4.000000,None,0.000096,...,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN
20942,21268,3704,2025/2026,30,2026-04-19T15:30:00Z,23.0,18,1.277778,None,0.000046,...,0,0,0,0,1,NaN,NaN,NaN,NaN,NaN
20943,21269,3704,2025/2026,31,2026-04-25T13:30:00Z,102.0,80,1.275000,None,0.000180,...,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN

In [40]:
df["points_p90_last_5"] = (
    (df["points_avg_last_5"] / df["minutes_avg_last_5"]) * 90
)

In [41]:
df["points_p90_last_3"] = (
    (df["points_avg_last_3"] / df["minutes_avg_last_3"]) * 90
)

In [42]:
df[["player_id", "matchday", "minutes_avg_last_3", "minutes_avg_last_5", "points_p90_last_5","points_p90_last_5"]].head(20)

,player_id,matchday,minutes_avg_last_3,minutes_avg_last_5,points_p90_last_5,points_p90_last_5
0,1,1,NaN,NaN,NaN,NaN
1,1,2,NaN,NaN,NaN,NaN
2,1,3,NaN,NaN,NaN,NaN
3,1,4,96.000000,NaN,NaN,NaN
4,1,5,96.333333,NaN,NaN,NaN
5,1,6,97.333333,96.2,58.191268,58.191268
6,1,7,97.000000,97.2,58.703704,58.703704
7,1,8,99.000000,98.0,63.734694,63.734694
8,1,9,98.333333,97.6,70.635246,70.635246
9,1,10,97.333333,97.8,80.061350,80.061350
10,1,11,95.333333,96.8,68.243802,68.243802
11,1,12,94.666667,96.2,69.604990,69.604990
12,1,13,95.666667,95.8,64.446764,64.446764
13,1,14,96.333333,95.6,60.062762,60.062762
14,1,15,101.000000,98.4,39.146341,39.146341
15,1,16,101.333333,99.4,60.482897,60.482897
16,1,17,102.333333,100.2,67.185629,67.185629
17,1,18,99.000000,100.4,72.430279,72.430279
18,1,19,99.000000,101.0,83.049505,83.049505
19,1,20,97.666667,98.2,105.580448,105.580448

In [ ]:
efficiency_cols = [
    "gewonnene_zweikaempfe",
    "schuesse_aufs_tor"
]

for col in efficiency_cols:
    df[f"{col}_filled"] = df[col].fillna(0)

    df[f"{col}_avg_last_3"] = (
        df.groupby(["player_id", "season"])[f"{col}_filled"]
        .shift(1)
        .rolling(window=3)
        .mean()
    )

    df[f"{col}_p90_last_3"] = df[f"{col}_avg_last_3"] / df["minutes_avg_last_3"] * 90
    df[f"{col}_p90_last_3"] = df[f"{col}_p90_last_3"].replace([np.inf, -np.inf], np.nan).fillna(0)  
    
    df = df.drop(columns=[f"{col}_filled", f"{col}_avg_last_3"])

In [45]:
df[["player_id", "matchday", "season", "schuesse_aufs_tor", "schuesse_aufs_tor_p90_last_3"]].head(20)

,player_id,matchday,season,schuesse_aufs_tor,schuesse_aufs_tor_p90_last_3
0,1,1,2024/2025,1,0.000000
1,1,2,2024/2025,0,0.000000
2,1,3,2024/2025,0,0.000000
3,1,4,2024/2025,0,0.312500
4,1,5,2024/2025,0,0.000000
5,1,6,2024/2025,0,0.000000
6,1,7,2024/2025,0,0.000000
7,1,8,2024/2025,0,0.000000
8,1,9,2024/2025,0,0.000000
9,1,10,2024/2025,0,0.000000
10,1,11,2024/2025,0,0.000000
11,1,12,2024/2025,0,0.000000
12,1,13,2024/2025,0,0.000000
13,1,14,2024/2025,0,0.000000
14,1,15,2024/2025,0,0.000000
15,1,16,2024/2025,2,0.000000
16,1,17,2024/2025,0,0.586319
17,1,18,2024/2025,0,0.606061
18,1,19,2024/2025,0,0.606061
19,1,20,2024/2025,0,0.000000

In [47]:
ratio_pairs = [
    ("erfolgreiche_paesse", "paesse_gesamt"), 
    ("gewonnene_zweikaempfe", "gewonnene_zweikaempfe_gesamt"),
    ("gewonnene_luftkaempfe", "gewonnene_luftkaempfe_gesamt"),
    ("erfolgreiche_tacklings", "tacklings_gesamt"),
    ("erfolgreiche_dribblings", "dribblings_gesamt"),
    ("schussgenauigkeit", "schussgenauigkeit_gesamt")
]

for succes_col, total_col in ratio_pairs:
    df[f"{succes_col}_filled"] = df[succes_col].fillna(0)
    df[f"{total_col}_filled"] = df[total_col].fillna(0)

    df[f"{succes_col}_sum_last_3"] = (
    df.groupby(["player_id", "season"])[f"{succes_col}_filled"]        
    .shift(1)
    .rolling(window=3)
    .sum()
    )

    df[f"{total_col}_sum_last_3"] = (
    df.groupby(["player_id", "season"])[f"{total_col}_filled"]        
    .shift(1)
    .rolling(window=3)
    .sum()
    )

    df[f"{succes_col}_ratio_last_3"] = df[f"{succes_col}_sum_last_3"] / df[f"{total_col}_sum_last_3"]
    df[f"{succes_col}_ratio_last_3"] = df[f"{succes_col}_ratio_last_3"].replace([np.inf, -np.inf], np.nan).fillna(0)

    df = df.drop(columns=[
        f"{succes_col}_filled",
        f"{succes_col}_sum_last_3",
        f"{total_col}_filled",
        f"{total_col}_sum_last_3"
    ])

In [48]:
df[["player_id", "matchday", "erfolgreiche_paesse_ratio_last_3", "gewonnene_zweikaempfe_ratio_last_3", "gewonnene_luftkaempfe_ratio_last_3"]].head(20)

,player_id,matchday,erfolgreiche_paesse_ratio_last_3,gewonnene_zweikaempfe_ratio_last_3,gewonnene_luftkaempfe_ratio_last_3
0,1,1,0.000000,0.000000,0.000000
1,1,2,0.000000,0.000000,0.000000
2,1,3,0.000000,0.000000,0.000000
3,1,4,0.838565,0.608696,0.416667
4,1,5,0.844828,0.500000,0.333333
5,1,6,0.761905,0.533333,0.375000
6,1,7,0.786885,0.500000,0.400000
7,1,8,0.836066,0.687500,0.400000
8,1,9,0.878613,0.705882,0.400000
9,1,10,0.902439,0.705882,0.333333
10,1,11,0.878049,0.636364,0.333333
11,1,12,0.884892,0.555556,0.400000
12,1,13,0.857143,0.454545,0.375000
13,1,14,0.859296,0.562500,0.444444
14,1,15,0.845361,0.550000,0.500000
15,1,16,0.866667,0.450000,0.571429
16,1,17,0.882759,0.391304,0.555556
17,1,18,0.855769,0.478261,0.714286
18,1,19,0.830508,0.571429,0.750000
19,1,20,0.833333,0.600000,0.636364

In [49]:
df[["player_id", "matchday", "erfolgreiche_tacklings_ratio_last_3", "erfolgreiche_dribblings_ratio_last_3", "schussgenauigkeit_ratio_last_3"]].head(20)

,player_id,matchday,erfolgreiche_tacklings_ratio_last_3,erfolgreiche_dribblings_ratio_last_3,schussgenauigkeit_ratio_last_3
0,1,1,0.000000,0.000000,0.0
1,1,2,0.000000,0.000000,0.0
2,1,3,0.000000,0.000000,0.0
3,1,4,0.400000,1.000000,1.0
4,1,5,0.333333,0.000000,0.0
5,1,6,0.333333,0.000000,0.0
6,1,7,0.500000,0.666667,0.0
7,1,8,0.714286,1.000000,0.0
8,1,9,0.714286,1.000000,0.0
9,1,10,0.666667,1.000000,0.0
10,1,11,0.750000,0.000000,0.0
11,1,12,0.666667,0.000000,0.0
12,1,13,1.000000,0.000000,0.0
13,1,14,0.666667,0.000000,0.0
14,1,15,0.400000,0.000000,0.0
15,1,16,0.428571,0.000000,0.0
16,1,17,0.400000,0.000000,1.0
17,1,18,0.500000,0.000000,1.0
18,1,19,0.500000,0.000000,1.0
19,1,20,0.500000,0.000000,0.0