In [2]:
import pandas as pd
import sqlite3
import numpy as np


# Player_stats_field
conn = sqlite3.connect("kickbase.db")

query_field_players = "SELECT * FROM player_stats_field"
query_goalkeeper = "SELECT * FROM player_stats_gk"
query_team_stats = "SELECT * FROM team_stats"


df_field_players = pd.read_sql_query(query_field_players, conn)
df_goalkeeper = pd.read_sql_query(query_goalkeeper, conn)
df_team_stats = pd.read_sql_query(query_field_players, conn)
conn.close()

df_field_players = df_field_players.sort_values(by=['player_id', 'season', 'matchday']).reset_index(drop=True)   
df_goalkeeper = df_goalkeeper.sort_values(by=['player_id', 'season', 'matchday']).reset_index(drop=True)

In [3]:
def points_avg_and_trend(df):
    df["points_filled"] = df['points'].fillna(0)

    df["points_avg_last_3"] = (
    df.groupby(["player_id", "season"])["points_filled"] 
    .shift(1)
    .rolling(window=3)
    .mean()
)
    df["points_avg_last_5"] = (
    df.groupby(["player_id", "season"])["points_filled"]
    .shift(1)
    .rolling(window=5)
    .mean()
)
    df["points_trend"] = df["points_avg_last_3"] - df["points_avg_last_5"]
    df = df.drop(columns=["points_filled"])
    return df

In [4]:
df_field_players = points_avg_and_trend(df_field_players)
df_field_players[["player_id", "matchday", "points", "points_avg_last_3", "points_avg_last_5", "points_trend"]].head(20)

,player_id,matchday,points,points_avg_last_3,points_avg_last_5,points_trend
0,1,1,46.0,NaN,NaN,NaN
1,1,2,40.0,NaN,NaN,NaN
2,1,3,34.0,NaN,NaN,NaN
3,1,4,92.0,40.000000,NaN,NaN
4,1,5,99.0,55.333333,NaN,NaN
5,1,6,52.0,75.000000,62.2,12.800000
6,1,7,70.0,81.000000,63.4,17.600000
7,1,8,70.0,73.666667,69.4,4.266667
8,1,9,144.0,64.000000,76.6,-12.600000
9,1,10,31.0,94.666667,87.0,7.666667
10,1,11,57.0,81.666667,73.4,8.266667
11,1,12,41.0,77.333333,74.4,2.933333
12,1,13,46.0,43.000000,68.6,-25.600000
13,1,14,39.0,48.000000,63.8,-15.800000
14,1,15,151.0,42.000000,42.8,-0.800000
15,1,16,97.0,78.666667,66.8,11.866667
16,1,17,71.0,95.666667,74.8,20.866667
17,1,18,108.0,106.333333,80.8,25.533333
18,1,19,149.0,92.000000,93.2,-1.200000
19,1,20,46.0,109.333333,115.2,-5.866667

In [5]:
def minutes_avg_and_trend(df):
    df["minutes_filled"] = df["minutes"].fillna(0)
    df["minutes_avg_last_3"] = (
    df.groupby(["player_id", "season"])["minutes_filled"]
    .shift(1)
    .rolling(window=3)
    .mean()
)
    df["minutes_avg_last_5"] = (
    df.groupby(["player_id", "season"])["minutes_filled"]
    .shift(1)
    .rolling(window=5)
    .mean()
)
    df.drop(columns=["minutes_filled"])
    return df

In [6]:
df_field_players = minutes_avg_and_trend(df_field_players)
df_field_players[["player_id", "matchday", "minutes", "minutes_avg_last_3", "minutes_avg_last_5"]].head(20)

    player_id  matchday  minutes  minutes_avg_last_3  minutes_avg_last_5
0           1         1       93                 NaN                 NaN
1           1         2       96                 NaN                 NaN
2           1         3       99                 NaN                 NaN
3           1         4       94           96.000000                 NaN
4           1         5       99           96.333333                 NaN
5           1         6       98           97.333333                96.2
6           1         7      100           97.000000                97.2
7           1         8       97           99.000000                98.0
8           1         9       95           98.333333                97.6
9           1        10       94           97.333333                97.8
10          1        11       95           95.333333                96.8
11          1        12       98           94.666667                96.2
12          1        13       96           95.666667                95.8
13          1        14      109           96.333333                95.6
14          1        15       99          101.000000                98.4
15          1        16       99          101.333333                99.4
16          1        17       99          102.333333               100.2
17          1        18       99           99.000000               100.4
18          1        19       95           99.000000               101.0
19          1        20       98           97.666667                98.2

In [7]:
def points_p90(df):
    df["points_p90_last_5"] = (
        (df["points_avg_last_5"] / df["minutes_avg_last_5"]) * 90
    )
    df["points_p90_last_3"] = (
    (df["points_avg_last_3"] / df["minutes_avg_last_3"]) * 90
)
    return df

In [8]:
df_field_players = points_p90(df_field_players)
df_field_players[["player_id", "matchday", "minutes_avg_last_3", "minutes_avg_last_5", "points_p90_last_5","points_p90_last_5"]].head(20)

,player_id,matchday,minutes_avg_last_3,minutes_avg_last_5,points_p90_last_5,points_p90_last_5
0,1,1,NaN,NaN,NaN,NaN
1,1,2,NaN,NaN,NaN,NaN
2,1,3,NaN,NaN,NaN,NaN
3,1,4,96.000000,NaN,NaN,NaN
4,1,5,96.333333,NaN,NaN,NaN
5,1,6,97.333333,96.2,58.191268,58.191268
6,1,7,97.000000,97.2,58.703704,58.703704
7,1,8,99.000000,98.0,63.734694,63.734694
8,1,9,98.333333,97.6,70.635246,70.635246
9,1,10,97.333333,97.8,80.061350,80.061350
10,1,11,95.333333,96.8,68.243802,68.243802
11,1,12,94.666667,96.2,69.604990,69.604990
12,1,13,95.666667,95.8,64.446764,64.446764
13,1,14,96.333333,95.6,60.062762,60.062762
14,1,15,101.000000,98.4,39.146341,39.146341
15,1,16,101.333333,99.4,60.482897,60.482897
16,1,17,102.333333,100.2,67.185629,67.185629
17,1,18,99.000000,100.4,72.430279,72.430279
18,1,19,99.000000,101.0,83.049505,83.049505
19,1,20,97.666667,98.2,105.580448,105.580448

In [9]:
def p90(df, efficiency_cols):

    for col in efficiency_cols:
        df[f"{col}_filled"] = df[col].fillna(0)

        df[f"{col}_avg_last_3"] = (
            df.groupby(["player_id", "season"])[f"{col}_filled"]
            .shift(1)
            .rolling(window=3)
            .mean()
        )

        df[f"{col}_p90_last_3"] = df[f"{col}_avg_last_3"] / df["minutes_avg_last_3"] * 90
        df[f"{col}_p90_last_3"] = df[f"{col}_p90_last_3"].replace([np.inf, -np.inf], np.nan).fillna(0)  
        
        df = df.drop(columns=[f"{col}_filled", f"{col}_avg_last_3"])
    
    return df

In [10]:
efficiency_cols = [
    "gewonnene_zweikaempfe",
    "schuesse_aufs_tor",
    "torschuss_vorlagen",
    "kreierte_grosschancen",
    "geklaerte_baelle",
    "abgefangene_baelle",
    "balleroberungen",
    "geblockte_baelle",
    "fehler_vor_gegentor",
    "begangene_fouls",
    "ballverluste"
]
df_field_players = p90(df_field_players, efficiency_cols)
df_field_players[["player_id", "matchday", "season", "schuesse_aufs_tor", "schuesse_aufs_tor_p90_last_3"]].head(20)

,player_id,matchday,season,schuesse_aufs_tor,schuesse_aufs_tor_p90_last_3
0,1,1,2024/2025,1,0.000000
1,1,2,2024/2025,0,0.000000
2,1,3,2024/2025,0,0.000000
3,1,4,2024/2025,0,0.312500
4,1,5,2024/2025,0,0.000000
5,1,6,2024/2025,0,0.000000
6,1,7,2024/2025,0,0.000000
7,1,8,2024/2025,0,0.000000
8,1,9,2024/2025,0,0.000000
9,1,10,2024/2025,0,0.000000
10,1,11,2024/2025,0,0.000000
11,1,12,2024/2025,0,0.000000
12,1,13,2024/2025,0,0.000000
13,1,14,2024/2025,0,0.000000
14,1,15,2024/2025,0,0.000000
15,1,16,2024/2025,2,0.000000
16,1,17,2024/2025,0,0.586319
17,1,18,2024/2025,0,0.606061
18,1,19,2024/2025,0,0.606061
19,1,20,2024/2025,0,0.000000

In [11]:
def ratios(df, ratio_pairs):
    for succes_col, total_col in ratio_pairs:
        df[f"{succes_col}_filled"] = df[succes_col].fillna(0)
        df[f"{total_col}_filled"] = df[total_col].fillna(0)

        df[f"{succes_col}_sum_last_3"] = (
        df.groupby(["player_id", "season"])[f"{succes_col}_filled"]        
        .shift(1)
        .rolling(window=3)
        .sum()
        )

        df[f"{total_col}_sum_last_3"] = (
        df.groupby(["player_id", "season"])[f"{total_col}_filled"]        
        .shift(1)
        .rolling(window=3)
        .sum()
        )

        df[f"{succes_col}_ratio_last_3"] = df[f"{succes_col}_sum_last_3"] / df[f"{total_col}_sum_last_3"]
        df[f"{succes_col}_ratio_last_3"] = df[f"{succes_col}_ratio_last_3"].replace([np.inf, -np.inf], np.nan).fillna(0)

        df = df.drop(columns=[
            f"{succes_col}_filled",
            f"{succes_col}_sum_last_3",
            f"{total_col}_filled",
            f"{total_col}_sum_last_3"
        ])

        return df

In [12]:
ratio_pairs = [
    ("erfolgreiche_paesse", "paesse_gesamt"), 
    ("gewonnene_zweikaempfe", "gewonnene_zweikaempfe_gesamt"),
    ("gewonnene_luftkaempfe", "gewonnene_luftkaempfe_gesamt"),
    ("erfolgreiche_tacklings", "tacklings_gesamt"),
    ("erfolgreiche_dribblings", "dribblings_gesamt"),
    ("schussgenauigkeit", "schussgenauigkeit_gesamt")
]
df_field_players = ratios(df_field_players, ratio_pairs)
df_field_players[["player_id", "matchday", "erfolgreiche_paesse_ratio_last_3", "gewonnene_zweikaempfe_ratio_last_3", "gewonnene_luftkaempfe_ratio_last_3"]].head(20)
df_field_players[["player_id", "matchday", "erfolgreiche_tacklings_ratio_last_3", "erfolgreiche_dribblings_ratio_last_3", "schussgenauigkeit_ratio_last_3"]].head(20)

KeyError: "['gewonnene_zweikaempfe_ratio_last_3', 'gewonnene_luftkaempfe_ratio_last_3'] not in index"

In [14]:
def form_trends(df, form_trend_cols):
    for col in form_trend_cols:
        df[f"{col}_filled"] = df[col].fillna(0)
        
        df[f"{col}_avg_last_3"] = (
            df.groupby(["player_id", "season"])[f"{col}_filled"]
            .shift(1).rolling(window=3).mean()
        )
        
        df[f"{col}_avg_last_5"] = (
            df.groupby(["player_id", "season"])[f"{col}_filled"]
            .shift(1).rolling(window=5).mean()
        )
        
        df[f"{col}_trend"] = df[f"{col}_avg_last_3"] - df[f"{col}_avg_last_5"]
        
        df = df.drop(columns=[f"{col}_filled"])

        return df

In [4]:
form_trend_cols = [
    "goals_own_team", 
    "goals_enemy_team", 
    "match_result", 
    "grade",
    "points_per_value"           
]

df_field_players = form_trends(df_field_players)

NameError: name 'form_trends' is not defined

In [16]:
df_field_players.head(20)

,id,player_id,season,matchday,date,points,minutes,points_per_minute,market_value,points_per_value,...,torschuss_vorlagen_p90_last_3,kreierte_grosschancen_p90_last_3,geklaerte_baelle_p90_last_3,abgefangene_baelle_p90_last_3,balleroberungen_p90_last_3,geblockte_baelle_p90_last_3,fehler_vor_gegentor_p90_last_3,begangene_fouls_p90_last_3,ballverluste_p90_last_3,erfolgreiche_paesse_ratio_last_3
0,32,1,2024/2025,1,2024-08-25T15:30:00Z,46.0,93,0.494624,None,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,33,1,2024/2025,2,2024-08-30T18:30:00Z,40.0,96,0.416667,None,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,34,1,2024/2025,3,2024-09-15T13:30:00Z,34.0,99,0.343434,None,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,35,1,2024/2025,4,2024-09-22T17:30:00Z,92.0,94,0.978723,None,NaN,...,0.000000,0.000000,3.437500,0.937500,0.625000,0.312500,0.000000,0.000000,0.312500,0.838565
4,36,1,2024/2025,5,2024-09-28T13:30:00Z,99.0,99,1.000000,None,NaN,...,0.311419,0.311419,3.737024,1.245675,0.311419,0.311419,0.000000,0.311419,0.622837,0.844828
5,37,1,2024/2025,6,2024-10-05T16:30:00Z,52.0,98,0.530612,None,NaN,...,0.308219,0.308219,3.390411,0.616438,0.308219,0.616438,0.000000,0.308219,0.308219,0.761905
6,38,1,2024/2025,7,2024-10-18T18:30:00Z,70.0,100,0.700000,None,NaN,...,0.618557,0.309278,3.092784,0.618557,0.309278,0.309278,0.000000,0.309278,0.618557,0.786885
7,39,1,2024/2025,8,2024-10-26T13:30:00Z,70.0,97,0.721649,None,NaN,...,0.303030,0.000000,2.424242,0.000000,1.515152,0.606061,0.000000,0.000000,0.303030,0.836066
8,40,1,2024/2025,9,2024-11-02T14:30:00Z,144.0,95,1.515789,None,NaN,...,0.305085,0.000000,3.050847,0.000000,1.525424,0.305085,0.305085,0.000000,0.305085,0.878613
9,41,1,2024/2025,10,2024-11-09T14:30:00Z,31.0,94,0.329787,None,NaN,...,0.000000,0.000000,3.698630,0.308219,1.849315,1.232877,0.308219,0.000000,0.000000,0.902439
10,42,1,2024/2025,11,2024-11-24T16:30:00Z,57.0,95,0.600000,None,NaN,...,0.000000,0.000000,4.720280,0.629371,0.944056,0.944056,0.314685,0.000000,0.000000,0.878049
11,43,1,2024/2025,12,2024-11-29T19:30:00Z,41.0,98,0.418367,None,NaN,...,0.000000,0.000000,4.753521,0.950704,0.633803,1.267606,0.316901,0.316901,0.000000,0.884892
12,44,1,2024/2025,13,2024-12-07T14:30:00Z,46.0,96,0.479167,None,NaN,...,0.000000,0.000000,3.763066,1.254355,0.313589,0.627178,0.313589,0.313589,0.000000,0.857143
13,45,1,2024/2025,14,2024-12-14T17:30:00Z,39.0,109,0.357798,None,NaN,...,0.000000,0.000000,2.802768,0.934256,0.622837,1.245675,0.311419,0.622837,0.000000,0.859296
14,46,1,2024/2025,15,2024-12-21T14:30:00Z,151.0,99,1.525253,None,NaN,...,0.297030,0.000000,2.079208,0.891089,0.594059,0.891089,0.000000,0.297030,0.000000,0.845361
15,47,1,2024/2025,16,2025-01-11T14:30:00Z,97.0,99,0.979798,None,NaN,...,0.296053,0.000000,3.552632,0.888158,0.888158,1.480263,0.000000,0.888158,0.592105,0.866667
16,48,1,2024/2025,17,2025-01-15T17:30:00Z,71.0,99,0.717172,None,NaN,...,0.293160,0.000000,4.104235,2.052117,1.172638,1.172638,0.000000,0.586319,0.586319,0.882759
17,49,1,2024/2025,18,2025-01-18T14:30:00Z,108.0,99,1.090909,None,NaN,...,0.000000,0.000000,5.757576,2.121212,1.818182,1.818182,0.000000,0.606061,0.606061,0.855769
18,50,1,2024/2025,19,2025-01-26T16:30:00Z,149.0,95,1.568421,None,NaN,...,0.000000,0.000000,3.636364,2.121212,1.818182,1.515152,0.000000,0.303030,0.000000,0.830508
19,51,1,2024/2025,20,2025-02-01T14:30:00Z,46.0,98,0.469388,None,NaN,...,0.000000,0.000000,4.607509,0.921502,0.921502,1.843003,0.000000,0.307167,0.000000,0.833333

In [3]:
def sums_cards_goals_assists(df):
    df["cards_total"] = df["yellow_cards"].fillna(0) + df["yellow_red_cards"].fillna(0) * 2 + df["red_cards"].fillna(0) * 3

    sum_cols = ["goals", "assists", "cards_total"]

    for col in sum_cols:
        df[f"{col}_sum_last_5"] = (
            df.groupby(["player_id", "season"])[col]
            .shift(1).rolling(window=5).sum().fillna(0)
        )
        
    df = df.drop(columns=["cards_total"])

    return df