In [ ]:
import pandas as pd
import sqlite3


conn = sqlite3.connect("kickbase.db")

query = "SELECT * FROM player_stats_field"

df = pd.read_sql_query(query, conn)

conn.close()
    
df = df.sort_values(by=['player_id', 'season', 'matchday']).reset_index(drop=True)

In [9]:
df["points_filled"] = df['points'].fillna(0)

In [10]:
df["points_avg_last_3"] = (
    df.groupby(["player_id", "season"])["points_filled"] 
    .shift(1)
    .rolling(window=3)
    .mean()
)

In [11]:
df["points_avg_last_5"] = (
    df.groupby(["player_id", "season"])["points_filled"]
    .shift(1)
    .rolling(window=5)
    .mean()
)

In [17]:
df["points_trend"] = df["points_avg_last_3"] - df["points_avg_last_5"]

In [18]:
df[["player_id", "matchday", "points", "points_avg_last_3", "points_avg_last_5", "points_trend"]].head(20)

,player_id,matchday,points,points_avg_last_3,points_avg_last_5,points_trend
0,1,1,46.0,NaN,NaN,NaN
1,1,2,40.0,NaN,NaN,NaN
2,1,3,34.0,NaN,NaN,NaN
3,1,4,92.0,40.000000,NaN,NaN
4,1,5,99.0,55.333333,NaN,NaN
5,1,6,52.0,75.000000,62.2,12.800000
6,1,7,70.0,81.000000,63.4,17.600000
7,1,8,70.0,73.666667,69.4,4.266667
8,1,9,144.0,64.000000,76.6,-12.600000
9,1,10,31.0,94.666667,87.0,7.666667
10,1,11,57.0,81.666667,73.4,8.266667
11,1,12,41.0,77.333333,74.4,2.933333
12,1,13,46.0,43.000000,68.6,-25.600000
13,1,14,39.0,48.000000,63.8,-15.800000
14,1,15,151.0,42.000000,42.8,-0.800000
15,1,16,97.0,78.666667,66.8,11.866667
16,1,17,71.0,95.666667,74.8,20.866667
17,1,18,108.0,106.333333,80.8,25.533333
18,1,19,149.0,92.000000,93.2,-1.200000
19,1,20,46.0,109.333333,115.2,-5.866667

In [ ]:
df = df.drop(columns=["points_filled"])

In [13]:
df["minutes_filled"] = df["minutes"].fillna(0)

In [14]:
df["minutes_avg_last_3"] = (
    df.groupby(["player_id", "season"])["minutes_filled"]
    .shift(1)
    .rolling(window=3)
    .mean()
)

In [15]:
df["minutes_avg_last_5"] = (
    df.groupby(["player_id", "season"])["minutes_filled"]
    .shift(1)
    .rolling(window=5)
    .mean()
)

In [16]:
df[["player_id", "matchday", "minutes", "minutes_avg_last_3", "minutes_avg_last_5"]].head(20)

    player_id  matchday  minutes  minutes_avg_last_3  minutes_avg_last_5
0           1         1       93                 NaN                 NaN
1           1         2       96                 NaN                 NaN
2           1         3       99                 NaN                 NaN
3           1         4       94           96.000000                 NaN
4           1         5       99           96.333333                 NaN
5           1         6       98           97.333333                96.2
6           1         7      100           97.000000                97.2
7           1         8       97           99.000000                98.0
8           1         9       95           98.333333                97.6
9           1        10       94           97.333333                97.8
10          1        11       95           95.333333                96.8
11          1        12       98           94.666667                96.2
12          1        13       96           95.666667                95.8
13          1        14      109           96.333333                95.6
14          1        15       99          101.000000                98.4
15          1        16       99          101.333333                99.4
16          1        17       99          102.333333               100.2
17          1        18       99           99.000000               100.4
18          1        19       95           99.000000               101.0
19          1        20       98           97.666667                98.2

In [ ]:
df.drop(columns=["minutes_filled"])